replace with simple script that unpacks and moves bionic binaries

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,9 +1,8 @@
 #!/bin/sh
 
-# this pack is valid for apps deployed on cedar-14 stack
-if [ "$STACK" = "cedar-14" ]; then
-  echo "wkhtmltopdf"
-  exit 0
+if [ "$STACK" = "heroku-18" ]; then
+	echo "wkhtmltopdf"
 else
-  exit 1
+	echo "ERROR: wkhtmltopdf does not work with this stack version!"
+	exit 1
 fi
